local cmd = vim.cmd -- Alias for vim.cmd
local map = vim.api.nvim_set_keymap -- Alias for setting keymap 
cmd([[let mapleader=" "]]) -- Sets leaderkey to space 
map('n', '<SPACE>', '<Nop>', { noremap = true }) -- nnoremap <SPACE> <Nop>
cmd([[let maplocalleader = "\\"]]) -- Sets local leader to backslash
map('n', '<leader>l', ':ls<CR>:b<space>', {noremap = true}) -- Show buffers
map('t', 'kj', [[<C-\><C-n>]], {noremap = true}) -- jk kj combination to leave term
map('t', 'jk', [[<C-\><C-n>]], {noremap = true}) -- same as above
map('n', 'kj', '<Esc>', {noremap = true}) -- s.a.a, but in normal mode
map('n', 'jk', '<Esc>', {noremap = true}) -- s.a.a
map('n', '<leader>t', ':term<CR>', {noremap = true}) -- open new term easily
map('n', '<leader>w', ':w!<CR>', {noremap = true}) -- write current buffer to file
map('n', '<leader>x', ':bd<CR>', {noremap = true}) -- quit current buffer
map('n', '<leader>f', ':e **/', {noremap = true}) -- quit current buffer
